-- -----------------------------------------------------
-- Table `USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER` (
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자ID',
  `USER_PASSWORD` VARCHAR(60) NOT NULL COMMENT '사용자 비밀번호',
  `USER_NAME` VARCHAR(60) NOT NULL COMMENT '사용자명',
  `EMAIL_ADDRESS` VARCHAR(100) NOT NULL COMMENT '이메일주소',
  `MOBILE_PHONE_NUMBER` VARCHAR(20) NOT NULL COMMENT '핸드폰번호',
  `PASSWORD_FAIL_COUNT` INT NULL DEFAULT 0 COMMENT '비밀번호 틀린 횟수',
  `PASSWORD_INIT_YN` VARCHAR(1) NULL DEFAULT 'N' COMMENT '비밀번호 초기화여부',
  `PASSWORD_MODIFY_DATETIME` VARCHAR(8) NULL DEFAULT NULL COMMENT '비밀번호 변경일시',
  `LANGUAGE` VARCHAR(2) NULL DEFAULT NULL COMMENT '사용자언어',
  `USER_STATUS` VARCHAR(1) NULL DEFAULT NULL COMMENT '사용자상태',
  `CREATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일시',
  `CREATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록자ID', 
  `UPDATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '수정일시', 
  `UPDATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '수정자ID', 
  PRIMARY KEY (`USER_ID`)
)
ENGINE = InnoDB
COMMENT = '사용자정보';


-- -----------------------------------------------------
-- Table `tmp`.`AUTHORITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUTHORITY` (
  `AUTHORITY_ID` VARCHAR(20) NOT NULL COMMENT '권한ID',
  `AUTHORITY_NAME` VARCHAR(60) NOT NULL COMMENT '권한명',
  `AUTHORITY_DESCRIPTION` VARCHAR(300) NULL COMMENT '권한설명',
  `USE_YN` VARCHAR(1) NULL COMMENT '사용여부',
  `CREATE_DATETIME` VARCHAR(14) NULL,
  `CREATE_USER_ID` VARCHAR(20) NULL,
  `UPDATE_DATETIME` VARCHAR(14) NULL,
  `UPDATE_USER_ID` VARCHAR(20) NULL,
  PRIMARY KEY (`AUTHORITY_ID`))
ENGINE = InnoDB
COMMENT = '권한정보';


-- -----------------------------------------------------
-- Table `tmp`.`USER_AUTHORITY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USER_AUTHORITY` (
  `USER_ID` VARCHAR(20) NOT NULL COMMENT '사용자ID',
  `AUTHORITY_ID` VARCHAR(20) NOT NULL COMMENT '권한ID',
  PRIMARY KEY (`USER_ID`, `AUTHORITY_ID`)
)
ENGINE = InnoDB
COMMENT = '사용자권한정보';


-- -----------------------------------------------------
-- Table `tmp`.`MENU`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MENU` (
  `MENU_ID` VARCHAR(6) NOT NULL,
  `MENU_PARENT_ID` VARCHAR(6) NULL,
  `MENU_NAME` VARCHAR(60) NOT NULL,
  `MENU_URL` VARCHAR(300) NOT NULL,
  `MENU_ORDER` INT NOT NULL,
  `USE_YN` VARCHAR(1) NULL,
  `CREATE_DATETIME` VARCHAR(14) NULL,
  `CREATE_USER_ID` VARCHAR(20) NULL,
  `UPDATE_DATETIME` VARCHAR(14) NULL,
  `UPDATE_USER_ID` VARCHAR(20) NULL,
  PRIMARY KEY (`MENU_ID`))
ENGINE = InnoDB
COMMENT = '메뉴정보';


-- -----------------------------------------------------
-- Table `tmp`.`RESOURCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCES` (
  `RESOURCE_ID` VARCHAR(4) NOT NULL,
  `MENU_ID` VARCHAR(6) NOT NULL,
  `RESOURCE_NAME` VARCHAR(60) NOT NULL,
  `RESOURCE_DESCRIPTION` VARCHAR(300) NULL,
  `RESOURCE_PATTERN` VARCHAR(100) NOT NULL,
  `RESOURCE_PATTERN_TYPE` VARCHAR(1) NULL,
  `RESOURCE_HTTP_METHOD` VARCHAR(10) NULL,
  `CREATE_DATETIME` VARCHAR(14) NULL,
  `CREATE_USER_ID` VARCHAR(20) NULL,
  `UPDATE_DATETIME` VARCHAR(14) NULL,
  `UPDATE_USER_ID` VARCHAR(20) NULL,
  PRIMARY KEY (`RESOURCE_ID`, `MENU_ID`)
  )
ENGINE = InnoDB
COMMENT = '리소스정보';


-- -----------------------------------------------------
-- Table `tmp`.`AUTHORITY_RESOURCES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUTHORITY_RESOURCES` (
  `AUTHORITY_ID` VARCHAR(20) NOT NULL COMMENT '권한ID',
  `RESOURCE_ID` VARCHAR(4) NOT NULL COMMENT '리소스ID',
  `CREATE_DATETIME` VARCHAR(14) NULL COMMENT '등록일시',
  `CREATE_USER_ID` VARCHAR(20) NULL COMMENT '등록자',
  PRIMARY KEY (`AUTHORITY_ID`, `RESOURCE_ID`)
 )
ENGINE = InnoDB
COMMENT = '리소스권한정보';


-- -----------------------------------------------------
-- Table `tmp`.`AUTHORITY_HIERARCHY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AUTHORITY_HIERARCHY` (
  `PARENT_ROLE_ID` VARCHAR(20) NOT NULL COMMENT '상위권한',
  `CHILD_ROLE_ID` VARCHAR(20) NOT NULL COMMENT '하위권한',
  PRIMARY KEY (`PARENT_ROLE_ID`, `CHILD_ROLE_ID`))
ENGINE = InnoDB
COMMENT = '권한계층테이블';


-- -----------------------------------------------------
-- Table `tmp`.`COMMON_CODE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMMON_CODE` (
  `CODE_ID` VARCHAR(20) NOT NULL COMMENT '코드ID',
  `CODE_NAME` VARCHAR(60) NOT NULL COMMENT '코드명',
  `USE_YN` VARCHAR(1) NULL COMMENT '사용여부',
  `CREATE_DATETIME` VARCHAR(14) NULL COMMENT '등록일시',
  `CREATE_USER_ID` VARCHAR(20) NULL COMMENT '등록자',
  `UPDATE_DATETIME` VARCHAR(14) NULL COMMENT '수정일시',
  `UPDATE_USER_ID` VARCHAR(20) NULL COMMENT '수정자',
  PRIMARY KEY (`CODE_ID`))
ENGINE = InnoDB
COMMENT = '공통코드';


-- -----------------------------------------------------
-- Table `tmp`.`COMMON_CODE_DETAIL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMMON_CODE_DETAIL` (
  `CODE_ID` VARCHAR(20) NOT NULL COMMENT '코드ID',
  `DETAIL_CODE_ID` VARCHAR(20) NOT NULL COMMENT '상세코드ID',
  `DETAIL_CODE_NAME` VARCHAR(60) NOT NULL COMMENT '상세코드명',
  `DETAIL_CODE_ORDER` INT NOT NULL COMMENT '상세코드순서',
  `USE_YN` VARCHAR(1) NULL COMMENT '사용여부',
  `CREATE_DATETIME` VARCHAR(14) NULL COMMENT '등록일시',
  `CREATE_USER_ID` VARCHAR(20) NULL COMMENT '등록자',
  `UPDATE_DATETIME` VARCHAR(14) NULL COMMENT '수정일시',
  `UPDATE_USER_ID` VARCHAR(20) NULL COMMENT '수정자',
  PRIMARY KEY (`CODE_ID`, `DETAIL_CODE_ID`),
  CONSTRAINT `fk_COMMON_CODE_DETAIL_COMMON_CODE1`
    FOREIGN KEY (`CODE_ID`)
    REFERENCES `COMMON_CODE` (`CODE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '공통상세코드';


-- -----------------------------------------------------
-- Table `tmp`.`QNA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `QNA` (
	`QNA_SNO` VARCHAR(20) NOT NULL COMMENT 'QNA일련번호' COLLATE 'utf8mb4_general_ci',
	`QUESTION_CATEGORY` VARCHAR(3) NULL DEFAULT NULL COMMENT '질문카테고리' COLLATE 'utf8mb4_general_ci',
	`QUESTION_TITLE` VARCHAR(100) NULL DEFAULT NULL COMMENT '질문제목' COLLATE 'utf8mb4_general_ci',
	`QUESTION_CONTENT` LONGTEXT NULL DEFAULT NULL COMMENT '질문내용' COLLATE 'utf8mb4_general_ci',
	`CREATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일시' COLLATE 'utf8mb4_general_ci',
	`CREATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_general_ci',
	`ANSWER` LONGTEXT NULL DEFAULT NULL COMMENT '답변내용' COLLATE 'utf8mb4_general_ci',
	`ANSWER_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '답변일시' COLLATE 'utf8mb4_general_ci',
	`ANSWER_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '답변자' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`QNA_SNO`) 
)
COMMENT='QNA'
COLLATE='utf8mb4_general_ci'
ENGINE=INNODB;

-- -----------------------------------------------------
-- Table `COMPANY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY` (
	`COMPANY_SNO` VARCHAR(20) NOT NULL COMMENT '법인일련번호' COLLATE 'utf8mb4_general_ci',
	`COMPANY_NAME` VARCHAR(50) NOT NULL COMMENT '법인명' COLLATE 'utf8mb4_general_ci',
	`ADDRESS` VARCHAR(100) NULL DEFAULT NULL COMMENT '주소' COLLATE 'utf8mb4_general_ci',
	`REP_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '대표자명' COLLATE 'utf8mb4_general_ci',
	`BIZ_NO` VARCHAR(12) NULL DEFAULT NULL COMMENT '사업자등록번호' COLLATE 'utf8mb4_general_ci',
	`COMPANY_TEL_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '법인전화번호' COLLATE 'utf8mb4_general_ci',
	`MANAGER_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자명' COLLATE 'utf8mb4_general_ci',
	`MANAGER_TEL_NO` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자전화번호' COLLATE 'utf8mb4_general_ci',
	`MANAGER_DEPARTMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자부서' COLLATE 'utf8mb4_general_ci',
	`MANAGER_EMAIL_ADDRESS` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자이메일주소' COLLATE 'utf8mb4_general_ci',
	`STATUS` VARCHAR(3) NULL DEFAULT 'Y' COMMENT '상태코드' COLLATE 'utf8mb4_general_ci',
	`CREATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일시' COLLATE 'utf8mb4_general_ci',
	`CREATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_general_ci',
	`UPDATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '수정일시' COLLATE 'utf8mb4_general_ci',
	`UPDATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`COMPANY_SNO`)
)
COMMENT='법인'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;

-- -----------------------------------------------------
-- Table `COMPANY HISTORY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COMPANY_HISTORY` (
	`COMPANY_HST_SNO` VARCHAR(20) NOT NULL COMMENT '법인이력일련번호' COLLATE 'utf8mb4_general_ci',
	`COMPANY_SNO` VARCHAR(20) NOT NULL COMMENT '법인일련번호' COLLATE 'utf8mb4_general_ci',
	`COMPANY_NAME` VARCHAR(50) NOT NULL COMMENT '법인명' COLLATE 'utf8mb4_general_ci',
	`ADDRESS` VARCHAR(100) NULL DEFAULT NULL COMMENT '주소' COLLATE 'utf8mb4_general_ci',
	`REP_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '대표자명' COLLATE 'utf8mb4_general_ci',
	`BIZ_NO` VARCHAR(12) NULL DEFAULT NULL COMMENT '사업자등록번호' COLLATE 'utf8mb4_general_ci',
	`COMPANY_TEL_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT '법인전화번호' COLLATE 'utf8mb4_general_ci',
	`MANAGER_NAME` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자명' COLLATE 'utf8mb4_general_ci',
	`MANAGER_TEL_NO` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자전화번호' COLLATE 'utf8mb4_general_ci',
	`MANAGER_DEPARTMENT` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자부서' COLLATE 'utf8mb4_general_ci',
	`MANAGER_EMAIL_ADDRESS` VARCHAR(50) NULL DEFAULT NULL COMMENT '담당자이메일주소' COLLATE 'utf8mb4_general_ci',
	`STATUS` VARCHAR(3) NULL DEFAULT 'Y' COMMENT '상태코드' COLLATE 'utf8mb4_general_ci',
	`CREATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '등록일시' COLLATE 'utf8mb4_general_ci',
	`CREATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'utf8mb4_general_ci',
	`UPDATE_DATETIME` VARCHAR(14) NULL DEFAULT NULL COMMENT '수정일시' COLLATE 'utf8mb4_general_ci',
	`UPDATE_USER_ID` VARCHAR(20) NULL DEFAULT NULL COMMENT '수정자' COLLATE 'utf8mb4_general_ci',
	PRIMARY KEY (`COMPANY_HST_SNO`)
)
COMMENT='법인이력'
COLLATE='utf8mb4_general_ci'
ENGINE=InnoDB
;